
set(CPACK_PACKAGE_VENDOR "BlueQuartz Software")

if(UNIX OR APPLE)
    set(CPACK_BINARY_BUNDLE "OFF")
    set(CPACK_BINARY_DEB "OFF")
    set(CPACK_BINARY_DRAGNDROP "OFF")
    set(CPACK_BINARY_FREEBSD "OFF")
    set(CPACK_BINARY_IFW "OFF")
    set(CPACK_BINARY_NSIS "OFF")
    set(CPACK_BINARY_OSXX11 "OFF")
    set(CPACK_BINARY_PACKAGEMAKER "OFF")
    set(CPACK_BINARY_PRODUCTBUILD "OFF")
    set(CPACK_BINARY_RPM "OFF")
    set(CPACK_BINARY_STGZ "OFF")
    set(CPACK_BINARY_TBZ2 "OFF")
    set(CPACK_BINARY_TGZ "ON")
    set(CPACK_BINARY_TXZ "OFF")
    set(CPACK_BINARY_TZ "OFF")
else()
    set(CPACK_BINARY_NSIS OFF)
    set(CPACK_BINARY_ZIP ON)
endif()

if(WIN32)
    set(DREAM3D_HOST_NAME "windows")
elseif(APPLE)
    set(DREAM3D_HOST_NAME "macos")
else()
    set(DREAM3D_HOST_NAME "linux")
endif()



if(DREAM3D_ENABLE_COMMERCIAL_BUILD)
    set(DREAM3D_MAIN_PACKAGE_NAME "DREAM3DNX")
else()
    set(DREAM3D_MAIN_PACKAGE_NAME "DREAM3D")
endif()

set(CPACK_COMPONENTS_ALL "Applications;Unspecified;license")
set(CPACK_PACKAGE_HOMEPAGE_URL "https://dream3d.bluequartz.net")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_SUMMARY "${DREAM3D_MAIN_PACKAGE_NAME} data analysis application. Built and maintained by BlueQuartz Software.")
set(CPACK_PACKAGE_NAME "${DREAM3D_MAIN_PACKAGE_NAME}")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY ${DREAM3D_MAIN_PACKAGE_NAME})
set(CPACK_PACKAGE_FILE_NAME "${DREAM3D_MAIN_PACKAGE_NAME}-${DREAM3DNXProj_VERSION}-${DREAM3D_HOST_NAME}-${CMAKE_SYSTEM_PROCESSOR}")



# THIS MUST BE THE LAST LINE OF THIS FILE BECAUSE ALL THE CPACK VARIABLES MUST BE
# DEFINED BEFORE CPack IS INCLUDED
INCLUDE(CPack)

